name: advent
root: ~/src/advent/2023/rust
windows:
  - bash:
      root: ~/src/advent/2023/rust
      layout: main-horizontal
      panes:
        - run:
            - just run day-01 part1
        - work:
            - just work day-01 part1
        - flamegraph:
            - just flamegraph day-01 part1
